#!/bin/sh /etc/rc.common
# OpenWRT procd init script for traffic-pinger.
# Manages /usr/bin/traffic-pinger as a respawning background service.
# Install: copy to /etc/init.d/traffic-pinger; then:
#   chmod +x /etc/init.d/traffic-pinger
#   /etc/init.d/traffic-pinger enable
#   /etc/init.d/traffic-pinger start

USE_PROCD=1
START=99
STOP=10

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/traffic-pinger
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
